name: Sync Fork with Upstream

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'

  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the forked repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false # We disable this because we will be using a different token

    - name: Configure git for GitHub Actions
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add the upstream repository
      run: git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPO.git

    - name: Fetch all branches from the upstream repository
      run: git fetch upstream

    - name: Merge upstream/main into forked repo main branch
      run: |
        git checkout main
        git merge upstream/main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
