name: Poll for changes to ReferencedUI

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run bash command
        run: |
          # Define the URL
          URL="https://emerynet.api.agoric.net/agoric/vstorage/data/published.vaultFactory.governance"

          # Run the command
          REFERENCED_UI=$(curl -s $URL | jq -r '.value' | jq -r '.values[]' | jq -r .body | sed 's/^#//' | jq -r .current.ReferencedUI.value)
          echo $REFERENCED_UI
