name: Poll for changes to ReferencedUI

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run bash command
        run: |
          # Define the URL
          URL="https://emerynet.api.agoric.net/agoric/vstorage/data/published.vaultFactory.governance"

          # Fetch the new value
          NEW_REFERENCED_UI=$(curl -s $URL | jq -r '.value' | jq -r '.values[]' | jq -r .body | sed 's/^#//' | jq -r .current.ReferencedUI.value)

          # Path to store the previous value
          OLD_REFERENCED_UI_FILE="./DEPLOYED_HASH"

          # Check if the previous value exists
          if [ -f "$OLD_REFERENCED_UI_FILE" ]; then
            # Read the previous value
            OLD_REFERENCED_UI=$(cat $OLD_REFERENCED_UI_FILE)
          else
            # File does not exist, set previous value to empty
            OLD_REFERENCED_UI=""
          fi

          # Output the values for the next step
          echo "NEW_VALUE=$NEW_REFERENCED_UI" >> $GITHUB_ENV
          echo "PREVIOUS_VALUE=$OLD_REFERENCED_UI" >> $GITHUB_ENV
      - name: Update DEPLOYED_HASH if value changed
        if: env.NEW_VALUE != env.PREVIOUS_VALUE
        run: |
          # Define the path to the previous value file
          REFERENCED_UI_FILE="./DEPLOYED_HASH"

          # Save the new value to the DEPLOYED_HASH file
          echo "$NEW_VALUE" > $REFERENCED_UI_FILE

          # Configure git and commit changes
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $REFERENCED_UI_FILE
          git commit -m "Update DEPLOYED_HASH with new value"
          git push
